### ISSUE TITLE
checkpoint hangs

### ISSUE THREAD

**Issue by jasongullifer** [RevolutionAnalytics/checkpoint#240] opened 2017-04-03 18:11 UTC
I'm on OS X 10.12.3 (Sierra), and I'm having an issue where calling checkpoint() hangs the R session. It hangs around "Scanning for packages used in this project." Running checkpoint with the verbose option produces the following error message. 
```
Scanning for packages used in this project
2017-04-03 13:49:34.390 Microsoft R Open[81300:1915664] 
Error loading /System/Library/PrivateFrameworks/Lookup.framework/Lookup:
dlopen(/System/Library/PrivateFrameworks/Lookup.framework/Lookup, 265): 
no suitable image found.  Did find:
/System/Library/PrivateFrameworks/Lookup.framework/Lookup: 
open() failed with errno=24
```
 
I tried again with a fresh install of MRO, and the same thing happened. I was able to use checkpoint successfully on my Windows PC.

**Comment by sfweller** [comment] 2017-04-03 18:57
It is not clear to us from the information you provided if this is a problem with the MRO application, or an issue with a particular R package you are attempting to install.

Can you please provide us the following information(this will help us determine what the issue is):

-  List of the R packages you are attempting to install with checkpoint, when you get the above error

-  Attach the following Apple log file from your Mac to this report:
    Go to /Applications/Utilities/Console directory on your Mac and copy/paste your Console.log file from
    this location to this issue.

Thanks a lot.

Stephen Weller
Microsoft R Open Product Team

**Comment by jasongullifer** [comment] 2017-04-04 14:47
Hi Stephen,

Thanks for your response. This is the output of sessionInfo() before running checkpoint()

```
locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] RevoUtils_10.0.2 tools_3.3.2     
```

The packages I'm trying to work with in my script are: dplyr, tidyr, ggplot2, stringr, lme4, and scales on a script open in RStudio (though the same behavior occurs with the official MRO application). 

I have attached my console.log file here: [console.txt](https://github.com/RevolutionAnalytics/checkpoint/files/893480/console.txt). I let the log run for about 10 mins after opening R and trying to run checkpoint() with ggplot2 loaded.

**Comment by jasongullifer** [comment] 2017-04-04 16:39
I also forgot to note that the error from the first post never came up while running this the chekpoint() command this time around (after 10 minutes at least). It just hung the R console. Perhaps this error is unrelated.

**Comment by andrie** [comment] 2017-04-12 17:17
Closing this issue, since it does not seem related to `checkpoint()`.

**Closed by andrie** 2017-04-12 17:17 UTC
Labels: question

**Comment by jasongullifer** [comment] 2017-04-12 17:22
I just saw this was closed. For what it's worth, the most recent version of MRO fixed the issue. Checkpoint no longer hangs!

**Comment by andrie** [comment] 2017-04-12 17:38
Great to know!  Thanks for the update.
