### ISSUE TITLE
Bug in checkpoint log while taking the checkpoint from local drive

### ISSUE THREAD

**Issue by dsritharan12** [RevolutionAnalytics/checkpoint#284] opened 2020-01-09 22:36 UTC
The below error is reported from checkpoint_log method and the mranURL is 'file:///c:/dev/snapshot'

Error in data.frame(timestamp = Sys.time(), snapshotDate = snapshotDate,  : 
  arguments imply differing number of rows: 1, 34, 0

The log returned from install.packages is as below
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘c:/dev/.checkpoint/2020-01-07/lib/x86_64-w64-mingw32/3.5.1’
(as ‘lib’ is unspecified)
package ‘ggplot2’ successfully unpacked and MD5 sums checked

The content type and size of the content is not getting emitted as it happen through a https:// url.

Can you please assist me on this?

**Comment by Hong-Revo** [comment] 2020-01-15 04:34
A lot of these issues stem from the shortcomings of `install.packages`, specifically, there is no way other than screen-scraping to detect the outcome of an install. I'm hoping to switch the backend to using the pkgdepends package, which will hopefully be a much more robust and flexible solution.

#280

**Comment by Hong-Revo** [comment] 2020-03-23 05:45
duplicate of #283

**Closed by Hong-Revo** 2020-03-23 05:45 UTC
