### ISSUE TITLE
Add checkpoint package to the ReproducibleResearch task view

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/checkpoint#147] opened 2014-11-07 01:11 UTC
Should be listed in http://mran.revolutionanalytics.com/taskview/info/?ReproducibleResearch

**Comment by andrie** [comment] 2015-01-10 12:20
I wrote to Max on Nov 15, 2014 and again on Jan 10, 2015.  Awaiting response.

**Comment by andrie** [comment] 2016-04-13 09:19
Closing, since `checkpoint` is mentioned at https://cran.r-project.org/web/views/ReproducibleResearch.html

**Closed by andrie** 2016-04-13 09:19 UTC
Labels: enhancement
